<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="State/RemoteData.fs" />
    <Compile Include="State/Shared.fs" />
    <Compile Include="Ui/Templates.fs" />
    <Compile Include="Pages/Home.fs" />
    <Compile Include="Pages/Games.fs" />
    <Compile Include="Pages/Servers.fs" />
    <Compile Include="Pages/Tournaments.fs" />
    <Compile Include="Pages/Members.fs" />
    <Compile Include="Pages/About.fs" />
    <Compile Include="Pages/Account.fs" />
    <Compile Include="App/App.fs" />
    <Compile Include="Ui/Layout.fs" />
    <Compile Include="Main.fs" />
    <Compile Include="Startup.fs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Community.Web.Shared\Community.Web.Shared.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Bolero" Version="0.*" />
    <PackageReference Include="Bolero.Build" Version="0.*" />
    <PackageReference Include="Bolero.HotReload" Version="0.*" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.*" />
  </ItemGroup>
</Project>
